name: gradle

# Controls when the action will run.
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-to-heroku:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: setup docker
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: heroku publish
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          ./gradlew bootJar
          docker build --load -t hndrs/artifacts:latest -f Dockerfile.app .
          docker tag hndrs/artifacts:latest registry.heroku.com/int-artifacts/web
          docker push registry.heroku.com/int-artifacts/web
          heroku container:release web --app int-artifacts
